haskell tester: make stack resolver version a setting
MarkUsProject/markus-autotesting pull request #526
Opened 2024-05-17 03:10 UTC by donny-wong

Make Stack Resolver a setting. It is a setting in two places. One is in the environment setting, where when we first install the tester, we will install this version in the setting. Second, is on the test settings where the instructor decides on the version. Currently there is only 1 resolver version to choose from. In the future, we will add to the list.

Note: 
in the file "server/autotest_server/__init__.py" we added the following lines:

                requirements_path = os.path.join(os.path.dirname(__file__), "../requirements.txt")
                subprocess.run([f"{default_env}/bin/pip", "install", "-r", requirements_path], check=True)

The reason for this is because when we import the config for the Haskell tester, we require the jsonschema module. This was not already present in the defaultvenv. 

2 Testing procedure:
1) Environment Setting: 
   - requires rebuilding docker environment for new env var STACK_RESOLVER
   - save Automtated Testing settings to see if that is successful
   - run a test for a submission to see if that is successful
 2) Test setting:
   - Rebuild schema: we have a new field "Resolver version" 
   - Save the Haskell Automated Test settings to include the Resolver version
   - Run a submission for a Haskell assignment to see if it is successful

2024-05-24 17:22 UTC, pretendWhale requested changes
@donny-wong looks great! I just noticed one issue with the changelog that needs fixing.

2024-05-24 17:22 UTC, pretendWhale commented on Changelog.md
> +- Omit skipped test cases in Python tester (#522)
Looks like the 2.4.3 changelog has been included twice here. Please remove this

2024-05-24 20:21 UTC, pretendWhale approved these changes

2024-05-26 23:11 UTC, david-yz-liu reviewed
@donny-wong Okay I think this is on the right track but still not aligned with what I'm looking for.

I _don't_ need a "default" LTS version to be specified as a global autotest server setting. I _do_ want a user setting, which is what you added in that PR, so that's good.

2024-05-26 23:11 UTC, david-yz-liu commented on server/autotest_server/__init__.py
> +                requirements_path = os.path.join(os.path.dirname(__file__), "../requirements.txt")
It's overkill to install all of the server dependencies here. In general I don't think it's a good idea to try to import `..config` from the haskell tester setup.

We can discuss later the best way to pass a "default" resolver as a setting, but for now I want you to keep the default as a constant (in the haskell tester setup file) and don't add it to the environment settings. See also my comment below about the schema.

2024-05-26 23:11 UTC, david-yz-liu commented on server/autotest_server/testers/haskell/settings_schema.json
> +          "enum": []
This shouldn't be an enum, it should just be a string field. The point is to allow the user to specify different stack LTS versions.

Stack LTS versions aren't like Python versions. You don't need to pre-install them, they will get installed when `stack build` is run. However it _is_ good to have a default value for this string field which is equal to the default LTS version (lts-16.17).

2024-06-01 00:43 UTC, david-yz-liu approved these changes

2024-06-01 00:44 UTC, merged